
import pptxgen from "pptxgenjs";

/**
 * 解析・編集後のデータからPPTXファイルを生成する
 */
export const createPptxFile = async (analysisResult) => {
  const pres = new pptxgen();
  pres.layout = 'LAYOUT_16x9';

  // タイトルスライド
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: "0F172A" };
  titleSlide.addText(analysisResult.presentationTitle || "AI Generated Presentation", {
    x: 0, y: "40%", w: "100%", align: "center", fontSize: 44, color: "38BDF8", bold: true
  });
  titleSlide.addText(analysisResult.summary || "Generated by Document to AI Movie", {
    x: 0, y: "55%", w: "100%", align: "center", fontSize: 18, color: "94A3B8"
  });

  // 各スライド
  analysisResult.slides.forEach((slide) => {
    const s = pres.addSlide();
    s.background = { color: "FFFFFF" };
    
    if (slide.imageUrl) {
      s.addImage({
        data: slide.imageUrl,
        x: 0, y: 0, w: "100%", h: "100%",
        sizing: { type: 'contain', w: 10, h: 5.625 }
      });
    } else {
      s.addText(slide.title, { x: 0.5, y: 0.5, w: 9, h: 1, fontSize: 32, color: "1E293B", bold: true });
      if (slide.content && slide.content.length > 0) {
        s.addText(slide.content.join("\n"), { x: 0.5, y: 1.5, w: 9, h: 4, fontSize: 18, color: "475569" });
      }
    }

    // ノートを追加
    s.addNotes(slide.notes);
  });

  const fileName = (analysisResult.presentationTitle || "presentation").replace(/[\\/:"*?<>|]/g, "_") + ".pptx";
  await pres.writeFile({ fileName });
};
